# Generated by Django 4.2 on 2023-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lingotype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
